{% set name = "PyAbel" %}
{% set version = "0.8.3" %}
{% set sha256 = "c6dc00b0af37be9a2dd20e667a4c805b53a05bfe24061936f45aed245ed21a4f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .  --verbose

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - pip
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.14
    - six >=1.10.0

test:
  imports:
    - abel
    - abel.lib
    - abel.tests
    - abel.tools

about:
  home: https://github.com/PyAbel/PyAbel
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'A Python package for forward and inverse Abel transforms'
  description: |
    PyAbel is a Python package that provides functions for the forward and inverse Abel transforms.
    The forward Abel transform takes a slice of a cylindrically symmetric 3D object and provides the
    2D projection of that object. The inverse abel transform takes a 2D projection and reconstructs
    a slice of the cylindrically symmetric 3D distribution.
  doc_url: http://pyabel.readthedocs.io/en/latest/readme_link.html
  dev_url: https://github.com/PyAbel/PyAbel

extra:
  recipe-maintainers:
    - DanHickstein
    - rth
    - stggh
    - DhrubajyotiDas
